### ISSUE TITLE
Remove private token?

### ISSUE THREAD

**Issue by AaronRoethe** [FrappaF/TradeInGo#1]
file location -> api/response.go

`cfg.AddDefaultHeader("X-Finnhub-Token", "*******")`

Is this token value supposed to be here? Is it possible for someone to abuse the website rules using your credentials? If that is the case, I would suggest removing this token value and adding it as an environment variable in a `.env` file or alternative. 

`cfg.AddDefaultHeader("X-Finnhub-Token", os.Getenv("token"))`

I found your repository through golangexample.com.

**Comment by FrappaF** [comment]
You're right!

**Comment by FrappaF** [comment]
I have updated the api/response.go with your suggestion
